new_page_extension: md
auto_deploy: false
sections:
  - type: directory
    path: src/posts
    label: Posts
    create: documents
    match: '**/*.md'
    new_doc_ext: md
    templates:
      - post
  - type: document
    path: src/data/bio.json
    label: Bio
upload_dir: static/assets
public_path: '/assets'
use_front_matter_path: false
file_templates: ':filename:'
build:
  preview_command: npm run build
  output_directory: public
